js/libs/jquery-1.11.3.js
js/libs/angular.min.js
js/libs/angular-route.min.js
js/libs/angular-resource.min.js
js/libs/angular-cookies.min.js
js/libs/angular-animate.js
js/libs/ui-bootstrap-tpls-0.14.3.min.js
js/libs/angular-animate.js
js/libs/moment.js
js/app.js
js/controllers.js
js/services.js